### ISSUE TITLE
Should navigation from the viewmodel to itself make it rerun the activate method?

### ISSUE THREAD

**Issue by rpawlaszek** [tyrsius/tuner#1]
Hi,

I got through your app and I really like the behavior in search.js/search.html and how clean the code is.

However, writing it exactly as you wrote it the this.nav.navigate(...) does not get my viewmodel rerun the activate method, and - eventually - there is no search. Nothing simpler: I added another method that is run when either activate or search runs. But - as asked in the title - should the navigation to itself rerun the activate method?

**Comment by kyeotic** [comment]
This application is _very_ unfinished and _very_ experimental. I was playing around with Aurelia. I have had very little time lately to continue with it, and it will likely remain in the current state for at least another two weeks as I remain incredibly busy moving into my new house.

**Comment by rpawlaszek** [comment]
Thanks for quick response and the code. It may be experimental, but is also very clean and helped me a lot to get around with few things in Aurelia. I understand that Aurelia is in its transitory phase, but just wanted to make sure about that option.

**Comment by kyeotic** [comment]
I believe that there is supposed to be a way to instruct a viewmodel/route to force reactivation on itself, but I can't find it at the moment

**Comment by rpawlaszek** [comment]
It seems reasonable that after the first activation of a viewmodel it remains active and is not reactivating later on. There is however one (but quite big) drawback of that not happening: moving around the history (pressing the browser's history buttons) having only the querystring changing does not change the contents on the page (that are driven by the search). There are additional navigate options (trigger and replace), but they do not change anything. At least for me. I guess I need to understand how routing and activation pipeline work.
